param([string]$Out)
# Two JPEGs generated by Windows' own WIC encoder, so the suite carries a
# 4:2:0 frame and a single-component (greyscale) frame that are NOT Adobe and
# carry no restart interval -- classes C:\Windows\Web is thin on.
Add-Type -AssemblyName PresentationCore
$w = 640; $h = 400
$stride = $w * 3
$buf = New-Object byte[] ($stride * $h)
for ($y = 0; $y -lt $h; $y++) {
  for ($x = 0; $x -lt $w; $x++) {
    $o = $y * $stride + $x * 3
    $buf[$o]     = [byte]((($x * 7 + $y * 3) -band 255))
    $buf[$o + 1] = [byte]((([math]::Floor(($x * $y) / 13)) -band 255))
    $buf[$o + 2] = [byte]((($x + $y * 5) -band 255))
  }
}
$bmp = [System.Windows.Media.Imaging.BitmapSource]::Create($w, $h, 96, 96, [System.Windows.Media.PixelFormats]::Bgr24, $null, $buf, $stride)
foreach ($q in 60, 85) {
  $enc = New-Object System.Windows.Media.Imaging.JpegBitmapEncoder
  $enc.QualityLevel = $q
  $enc.Frames.Add([System.Windows.Media.Imaging.BitmapFrame]::Create($bmp))
  $fs = [System.IO.File]::Create((Join-Path $Out ("wic_color_q$q.jpg")))
  $enc.Save($fs); $fs.Close()
}
$gbuf = New-Object byte[] ($w * $h)
for ($y = 0; $y -lt $h; $y++) {
  for ($x = 0; $x -lt $w; $x++) { $gbuf[$y * $w + $x] = [byte]((($x * 3 + $y * 11) -band 255)) }
}
$g = [System.Windows.Media.Imaging.BitmapSource]::Create($w, $h, 96, 96, [System.Windows.Media.PixelFormats]::Gray8, $null, $gbuf, $w)
foreach ($q in 50, 80) {
  $enc2 = New-Object System.Windows.Media.Imaging.JpegBitmapEncoder
  $enc2.QualityLevel = $q
  $enc2.Frames.Add([System.Windows.Media.Imaging.BitmapFrame]::Create($g))
  $fs2 = [System.IO.File]::Create((Join-Path $Out ("wic_gray_q$q.jpg")))
  $enc2.Save($fs2); $fs2.Close()
}
Write-Output "(b) 4 WIC JPEGs written to $Out"
