#!/usr/bin/env python
# gen_states.py -- emits src/state_tab.rs, the bit-history state machine.
# Byte-identical regeneration required; integer-only; list/sort-based
# enumeration (no set/dict iteration order anywhere); newline='\n'.
#
# CONSTRUCTION (the auditable algorithm, zpaq-style; attribution: Matt
# Mahoney's zpaq bit-history states, restated here for P(bit==0)):
#
# A state is (n0, n1, last): n0 = count of 0-bits seen, n1 = of 1-bits,
# last = the most recent bit (tracked only for "doubled" pairs).
#   POLARITY: bit 0 increments n0. n0 is the ZEROS count. p is P(0) from n0.
# - validity: with (hi, lo) = (max, min) of the pair: lo < 6 and
#   hi <= BOUND[lo], BOUND = [20, 48, 15, 8, 6, 5].
# - a valid pair carries TWO states (last=0 and last=1) iff lo > 0 and
#   n0+n1 <= 17; else one.
# - update on bit b: the same-side count += 1, the OPPOSITE count is
#   discounted to min(n, 7); then while the pair is invalid it is reduced:
#   if lo < 2: hi -= 1; else hi = (hi*(lo-1) + lo//2)//lo; lo -= 1.
# - enumeration: all valid pairs sorted by (n0+n1, n1); within a doubled
#   pair the last=0 variant first; ids from 0; state 0 = (0,0).
# - transition from (n0,n1,·) on b: reduce(update) -> the last=b variant if
#   the target pair is doubled, else its single state.

BOUND = [20, 48, 15, 8, 6, 5]

def valid(n0, n1):
    hi, lo = max(n0, n1), min(n0, n1)
    return lo < 6 and hi <= BOUND[lo]

def doubled(n0, n1):
    return min(n0, n1) > 0 and n0 + n1 <= 17

def discount(n):
    return n if n < 7 else 7

def reduce_pair(n0, n1):
    while not valid(n0, n1):
        if n0 >= n1:
            hi, lo = n0, n1
        else:
            hi, lo = n1, n0
        if lo < 2:
            hi -= 1
        else:
            hi = (hi * (lo - 1) + lo // 2) // lo
            lo -= 1
        if n0 >= n1:
            n0, n1 = hi, lo
        else:
            n0, n1 = lo, hi
    return n0, n1

def next_pair(n0, n1, b):
    if b == 0:
        return reduce_pair(n0 + 1, discount(n1))
    return reduce_pair(discount(n0), n1 + 1)

# enumerate valid pairs
pairs = []
for n0 in range(0, 49):
    for n1 in range(0, 49):
        if valid(n0, n1):
            pairs.append((n0, n1))
pairs.sort(key=lambda p: (p[0] + p[1], p[1]))

# assign ids: doubled pairs get (last=0, last=1) in that order
states = []  # (n0, n1, last or -1)
sid = {}     # (n0, n1, last_key) -> id ; last_key = -1 for single
for (n0, n1) in pairs:
    if doubled(n0, n1):
        sid[(n0, n1, 0)] = len(states); states.append((n0, n1, 0))
        sid[(n0, n1, 1)] = len(states); states.append((n0, n1, 1))
    else:
        sid[(n0, n1, -1)] = len(states); states.append((n0, n1, -1))

N = len(states)
assert N <= 256, N
assert states[0][:2] == (0, 0), states[0]

def target(n0, n1, b):
    t0, t1 = next_pair(n0, n1, b)
    if doubled(t0, t1):
        return sid[(t0, t1, b)]
    return sid[(t0, t1, -1)]

rows = []
for (n0, n1, last) in states:
    rows.append([target(n0, n1, 0), target(n0, n1, 1), n0, n1])
while len(rows) < 256:
    rows.append([len(rows), len(rows), 0, 0])  # unused rows: self-loops

# polarity tripwire: the all-zeros walk from state 0 keeps n1 == 0
s = 0
for step in range(20):
    s = rows[s][0]
    assert rows[s][3] == 0, (step, s, rows[s])
    assert rows[s][2] >= 1
# every target in range
for r in rows[:N]:
    assert r[0] < N and r[1] < N

lines = []
lines.append("//! state_tab.rs -- the bit-history state machine, GENERATED by")
lines.append("//! tools/gen_states.py (byte-identical regeneration; the construction")
lines.append("//! algorithm is documented there). Attribution: Matt Mahoney's zpaq")
lines.append("//! bit-history states, restated for this codebase's P(bit==0) polarity:")
lines.append("//! BIT 0 INCREMENTS N0; n0 is the zeros count.")
lines.append("//!")
lines.append("//! The cycle reading (index.html:220, :730): the site's cells live in a")
lines.append("//! small set of named conditions with successor rules; these are ours.")
lines.append("")
lines.append(f"pub const NSTATE: usize = {N};")
lines.append("/// NEX[s] = [next state on bit 0, next on bit 1, n0(s), n1(s)]")
lines.append("pub const NEX: [[u8; 4]; 256] = [")
for r in rows:
    lines.append(f"    [{r[0]}, {r[1]}, {r[2]}, {r[3]}],")
lines.append("];")
open('src/state_tab.rs', 'w', newline='\n').write("\n".join(lines) + "\n")
print(f"state_tab.rs written: {N} states")
