//! lit.rs -- the literature, reimplemented from its own definitions.
//!
//! v7 closed the mathematics and I answered "is it novel?" with an opinion.
//! This module answers it the way this project answers everything else: by
//! building the prior art's constructions and measuring whether they
//! reproduce ours. A coincidence measured settles the question; a citation
//! read only relocates it.
//!
//! Each construction below is implemented from the DEFINITION the source
//! gives, not from our restatement of it, so that agreement is evidence and
//! not an artefact of how we chose to write it down.
//!
//! ## What the literature actually contains
//!
//! * **Blaum, Bruck & Vardy, "Interleaving schemes for multidimensional
//!   cluster errors", IEEE Trans. Inf. Theory 44 (1998) 730-743.** The
//!   `t`-interleaved array: every CONNECTED COMPONENT of area `t` must carry
//!   DISTINCT integers. The objective is to minimise the number of colours
//!   (the interleaving degree) for a given `t`. Also introduces lattice
//!   interleavers.
//! * **Perfect colourings of the square grid.** The colourings of `Z^2` with
//!   up to nine colours are catalogued, and the standard example given is
//!   `colour(x, y) = (y - x) mod 3`.
//! * **Lattice interleavers / dispersion.** Colour by the coset of a
//!   sublattice; the figure of merit is the minimum distance between two
//!   cells of the same colour.
//!
//! ## Where ours differs, stated so the measurement can confirm or refute it
//!
//! Three differences, and only the third is interesting:
//!
//! 1. **Distinctness against multiplicity.** BBV require all-distinct
//!    colours on a cluster; we fix three colours and bound the MULTIPLICITY
//!    at `ceil(L/3)`. With three colours, distinctness on any cluster of four
//!    cells is impossible outright, so their criterion cannot even be posed
//!    for our alphabet -- see `t_interleaved_degree_needed`.
//! 2. **Clusters against lines.** Their bursts are connected regions measured
//!    by area; ours are four specified LINE geometries. A line of `L` cells
//!    is a connected component of area `L`, so our constraint is a strict
//!    RELAXATION of theirs restricted to four shapes.
//! 3. **`Z^2` against a finite array read as a tape.** This is the real
//!    difference. The lattice literature colours the INFINITE lattice, where
//!    there is no row-major serialisation and therefore no phase slip at a
//!    row boundary. Our answer depends on `n mod 3`, `gcd(n, L)` and
//!    `gcd(n-1, L)` -- quantities with no meaning in `Z^2`. Everything in
//!    v5/v7 that is width-dependent comes from the tape geometry alone, and
//!    `spatial_only_is_width_free` measures exactly that.

use crate::optimum::{floor_of, worst_of, Geom};

/// The catalogued perfect colouring of the square grid, written the way the
/// source writes it: `colour(x, y) = (y - x) mod 3`, with `x` the column and
/// `y` the row.
///
/// Deliberately NOT written as one of our `(a,b)` arms, so that finding it
/// equals one is a measurement.
pub fn perfect_colouring(r: usize, c: usize) -> u8 {
    // (y - x) mod 3 with y = r, x = c, taken positive
    (((r as i64 - c as i64) % 3 + 3) % 3) as u8
}

pub fn perfect_colouring_grid(n: usize) -> Vec<u8> {
    (0..n * n).map(|j| perfect_colouring(j / n, j % n)).collect()
}

/// Is `(dr, dc)` in the sublattice generated by `v1` and `v2`? Solved from
/// the definition -- `(dr,dc) = s*v1 + t*v2` with `s`, `t` INTEGERS -- by
/// Cramer's rule, so the test is integrality of the two numerators.
pub fn in_sublattice(dr: i64, dc: i64, v1: (i64, i64), v2: (i64, i64)) -> Option<bool> {
    let det = v1.0 * v2.1 - v1.1 * v2.0;
    if det == 0 {
        return None;
    }
    let s_num = dr * v2.1 - dc * v2.0;
    let t_num = dc * v1.0 - dr * v1.1;
    Some(s_num % det == 0 && t_num % det == 0)
}

/// A **lattice interleaver**: colour each cell by which coset of the
/// sublattice it falls in.
///
/// Built GEOMETRICALLY and not algebraically -- cells are grouped by
/// `in_sublattice` on their difference, and cosets are numbered in the order
/// they are first met. Nothing here assumes the answer is a linear form mod
/// 3, which is the whole point: that index-3 cosets of `Z^2` turn out to be
/// the level sets of a linear form is then something the measurement finds
/// rather than something the code was told.
///
/// `None` when the generators are degenerate, or when the index does not
/// come out equal to the number of cosets actually seen (which means the grid
/// was too small to exhibit them all).
pub fn lattice_colouring(n: usize, v1: (i64, i64), v2: (i64, i64)) -> Option<Vec<u8>> {
    let det = v1.0 * v2.1 - v1.1 * v2.0;
    if det == 0 {
        return None;
    }
    let idx = det.unsigned_abs() as usize;
    if idx == 0 || idx > 16 {
        return None;
    }
    let mut reps: Vec<(i64, i64)> = Vec::new();
    let mut class = vec![0u8; n * n];
    for (j, slot) in class.iter_mut().enumerate() {
        let (r, c) = ((j / n) as i64, (j % n) as i64);
        let mut found = None;
        for (k, rep) in reps.iter().enumerate() {
            if in_sublattice(r - rep.0, c - rep.1, v1, v2)? {
                found = Some(k);
                break;
            }
        }
        let k = match found {
            Some(k) => k,
            None => {
                reps.push((r, c));
                reps.len() - 1
            }
        };
        *slot = k as u8;
    }
    if reps.len() != idx {
        return None; // the grid did not exhibit every coset
    }
    Some(class)
}

/// **The BBV criterion, as they state it**: every connected component of area
/// `t` carries distinct integers. Returns the smallest `t` at which this
/// colouring FAILS, i.e. the largest cluster it keeps distinct plus one.
///
/// Implemented on the 4-neighbour grid, which is the connectivity model the
/// source uses.
pub fn t_interleaved_breaks_at(class: &[u8], n: usize) -> usize {
    // t = 2 fails iff two orthogonally adjacent cells share a colour
    for r in 0..n {
        for c in 0..n {
            let k = class[r * n + c];
            if c + 1 < n && class[r * n + c + 1] == k {
                return 2;
            }
            if r + 1 < n && class[(r + 1) * n + c] == k {
                return 2;
            }
        }
    }
    // t = 3: any connected triple. With 3 colours a connected triple must be
    // a rainbow, so search the L-shapes and the straight triples.
    for r in 0..n {
        for c in 0..n {
            let at = |rr: usize, cc: usize| class[rr * n + cc];
            let k = at(r, c);
            if c + 2 < n && at(r, c + 2) == k {
                return 3;
            }
            if r + 2 < n && at(r + 2, c) == k {
                return 3;
            }
            if r + 1 < n && c + 1 < n && at(r + 1, c + 1) == k {
                return 3;
            }
            if r + 1 < n && c > 0 && at(r + 1, c - 1) == k {
                return 3;
            }
        }
    }
    4
}

/// How many colours BBV's criterion NEEDS for a given `t`, from the
/// pigeonhole they themselves use: a connected component of area `t` has `t`
/// cells that must all differ, so at least `t` colours.
///
/// This is the sentence that separates the two problems: at `t = 4` their
/// criterion needs four colours and we have three, so their question cannot
/// even be POSED for our alphabet. Ours is the multiplicity relaxation of it.
pub fn t_interleaved_degree_needed(t: usize) -> usize {
    t
}

/// The lattice-interleaver figure of merit: the minimum `L1` distance between
/// two distinct cells of the same colour. Larger is better, and it is a
/// SPATIAL measure with no reference to any read order.
pub fn dispersion(class: &[u8], n: usize) -> usize {
    let mut best = usize::MAX;
    for r1 in 0..n {
        for c1 in 0..n {
            let k = class[r1 * n + c1];
            for r2 in r1..n {
                for c2 in 0..n {
                    if r2 == r1 && c2 <= c1 {
                        continue;
                    }
                    if class[r2 * n + c2] != k {
                        continue;
                    }
                    let d = r2.abs_diff(r1) + c2.abs_diff(c1);
                    if d < best {
                        best = d;
                    }
                }
            }
        }
    }
    best
}

/// The three SPATIAL geometries only -- row, column, anti-diagonal -- with the
/// tape left out. These are the ones the lattice literature's objects live
/// under, because `Z^2` has no serialisation.
pub fn spatial_at_floor(class: &[u8], n: usize, l: usize) -> bool {
    [Geom::Row, Geom::Col, Geom::Diag]
        .iter()
        .all(|&g| worst_of(class, n, l, g).map(|w| w == floor_of(l)).unwrap_or(true))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::optimum::{linear_class, worst_all};
    use crate::thirds::linear_verdict;

    /// **The coincidence, measured.** The literature's catalogued example
    /// colouring of the square grid is `(y - x) mod 3`. Written from that
    /// definition and compared cell for cell, it IS our arm `(1,2)` -- one of
    /// exactly two that reach the burst floor at `n = 2 (mod 3)`.
    ///
    /// So the spatial half of v5/v7's result is about an object the
    /// literature already has a name and a catalogue entry for.
    #[test]
    fn the_catalogued_perfect_colouring_is_our_optimal_arm() {
        for n in 2..=40usize {
            assert_eq!(
                perfect_colouring_grid(n),
                linear_class(1, 2, n),
                "(y-x) mod 3 is not arm (1,2) at n={n}"
            );
        }
        // and (1,2) is one of the two arms our theorem names at n = 2 (mod 3)
        assert!(crate::optimum::linear_solutions(32).contains(&(1, 2)));
        assert_eq!(crate::optimum::linear_solutions(32).len(), 2);
    }

    /// The lattice-interleaver recipe lands in the same nine-member family we
    /// searched -- which is the second half of "not novel": we did not invent
    /// the family, we enumerated one the literature builds by another route.
    ///
    /// The colouring is built geometrically, by grouping cells whose
    /// difference lies in the sublattice, so the agreement below is a
    /// measurement and not a restatement.
    #[test]
    fn lattice_matches_a_linear_arm() {
        let n = 24usize;
        let mut matched = 0usize;
        let mut tried = 0usize;
        // every index-3 sublattice of Z^2, by a pair of generators
        for v1 in [(1i64, 1i64), (1, -1), (1, 2), (2, 1), (3, 0), (0, 3), (1, 0), (0, 1)] {
            for v2 in [(0i64, 3i64), (3, 0), (1, 2), (2, 1), (1, -1), (1, 1)] {
                let det = v1.0 * v2.1 - v1.1 * v2.0;
                if det.unsigned_abs() != 3 {
                    continue;
                }
                let Some(built) = lattice_colouring(n, v1, v2) else { continue };
                tried += 1;
                // agrees with SOME linear arm up to a relabelling of colours
                let agrees = (0..3).flat_map(|a| (0..3).map(move |b| (a, b))).any(|(a, b)| {
                    let arm = linear_class(a, b, n);
                    let mut map = [None::<u8>; 3];
                    let mut back = [None::<u8>; 3];
                    for (x, y) in built.iter().zip(arm.iter()) {
                        match (map[*x as usize], back[*y as usize]) {
                            (None, None) => {
                                map[*x as usize] = Some(*y);
                                back[*y as usize] = Some(*x);
                            }
                            (Some(v), Some(w)) if v == *y && w == *x => {}
                            _ => return false,
                        }
                    }
                    true
                });
                assert!(agrees, "lattice ({v1:?},{v2:?}) is outside the linear family");
                matched += 1;
            }
        }
        assert!(tried >= 4, "only {tried} index-3 sublattices exercised");
        assert_eq!(matched, tried, "some lattice interleaver escaped the family");
    }

    /// **The separation, measured.**    /// **The separation, measured.** BBV's criterion is DISTINCTNESS on a
    /// connected cluster, and with three colours it cannot survive a cluster
    /// of four cells -- their own pigeonhole needs `t` colours for area `t`.
    /// So their question cannot be posed for our alphabet, and ours is its
    /// multiplicity relaxation rather than an instance of it.
    #[test]
    fn the_bbv_criterion_cannot_be_posed_with_three_colours() {
        assert_eq!(t_interleaved_degree_needed(4), 4);
        assert!(t_interleaved_degree_needed(4) > 3);
        // even our best arm breaks their criterion at t = 4 or earlier
        for n in [16usize, 24, 32] {
            for &(a, b) in &[(1usize, 2usize), (2, 1)] {
                let cl = linear_class(a, b, n);
                let t = t_interleaved_breaks_at(&cl, n);
                assert!(t <= 4, "arm ({a},{b}) at n={n} survived to t={t} with 3 colours");
            }
        }
    }

    /// **Where ours is not theirs.** The lattice literature colours the
    /// INFINITE lattice, so its objects have no row-major read order and no
    /// phase slip. Measured: over the three SPATIAL geometries alone, the
    /// verdict is width-free -- an arm that works at one `n` works at every
    /// `n` -- and every width dependence in v5/v7 comes from the tape.
    #[test]
    fn spatial_only_is_width_free_and_the_tape_is_where_n_enters() {
        for l in [6usize, 8, 9, 11, 12, 13] {
            for &(a, b) in &[(1usize, 2usize), (2, 1), (1, 1), (0, 1), (1, 0)] {
                // the spatial verdict is the same at every width
                let verdicts: Vec<bool> = (14..=36)
                    .filter(|&n| l <= n)
                    .map(|n| spatial_at_floor(&linear_class(a, b, n), n, l))
                    .collect();
                assert!(
                    verdicts.windows(2).all(|w| w[0] == w[1]),
                    "the SPATIAL verdict moved with n for ({a},{b}), L={l}"
                );
                // and the spatial verdict is exactly the three conditions,
                // with no reference to n at all
                let want = b % 3 != 0 && a % 3 != 0 && a % 3 != b % 3;
                assert_eq!(verdicts[0], want, "({a},{b}), L={l}");
            }
        }

        // whereas the FULL verdict does move with n -- and only because of
        // the tape. (1,2) at L=12 works at n=32 and fails at n=30.
        assert!(worst_all(&linear_class(1, 2, 32), 32, 12).at_floor(12));
        assert!(!worst_all(&linear_class(1, 2, 30), 30, 12).at_floor(12));
        assert!(spatial_at_floor(&linear_class(1, 2, 30), 30, 12));
        assert!(linear_verdict(32, 12) && !linear_verdict(30, 12));
    }

    /// Dispersion is a spatial measure and it too is width-free, which is the
    /// same point from the lattice side.
    #[test]
    fn dispersion_is_width_free() {
        let d: Vec<usize> = [12usize, 16, 20, 24]
            .iter()
            .map(|&n| dispersion(&linear_class(1, 2, n), n))
            .collect();
        assert!(d.windows(2).all(|w| w[0] == w[1]), "dispersion moved with n: {d:?}");
        assert!(d[0] >= 2, "the optimal arm should separate same-colour cells");
    }
}
