/* node tools/sequences.js [N] — the integer sequences this construction makes.
 *
 * The README ends on the one thing its author could not place: the fold itself,
 * "held loosely". A construction that is genuinely new leaves fingerprints --
 * sequences nobody has written down. A construction that is a rediscovery
 * leaves sequences that are already in the literature under another name.
 *
 * Either answer is worth having, and neither can be had without the numbers.
 * So this prints them, in the b-file form the OEIS takes, and says what each
 * one counts so a search can be done by description as well as by terms.
 *
 *   node tools/sequences.js            # a readable summary
 *   node tools/sequences.js --bfiles   # write b-files into tools/seq/
 *
 * Nothing here is part of the site. It reads the site's own functions so the
 * sequences cannot drift from what the pages actually draw. */

const path = require("path");
const {loadPage} = require(__dirname + "/domharness.js");
const {run: idx} = loadPage(path.join(__dirname, "..", "index.html"));
const {run: spec} = loadPage(path.join(__dirname, "..", "spec.html"));

const N = parseInt(process.argv.find(a => /^\d+$/.test(a)) || "1023", 10);
const BFILES = process.argv.indexOf("--bfiles") >= 0;

/* ---- helpers, all reading the site's own code ---------------------------- */

const gridSig = k => JSON.stringify(idx(`gridOf(${k}).g`));
const stalkOf = k => spec(`stalkOf(BigInt(${Math.abs(k)}), ${k < 0})`);
const regionsOf = k => spec(`(() => {
  const st = stalkOf(BigInt(${Math.abs(k)}), ${k < 0});
  return regions(st.cells, st.n);
})()`);
const lit = slots => slots.filter(s => s.v !== 0).length;

/* ---- the sequences ------------------------------------------------------- */

const SEQS = [];

/* 1. how many distinct grids the first n integers draw.
      The landing page states the endpoint of this (644 grids for 1..1023) as
      a fact about the drawing; as a sequence it is a fingerprint. */
{
  const seen = new Set(), terms = [];
  for(let k = 1; k <= N; k++){ seen.add(gridSig(k)); terms.push(seen.size); }
  SEQS.push({
    id: "grids",
    name: "Number of distinct fold-grids drawn by the integers 1..n",
    note: "Two integers draw the same grid when a trailing zero and a padding "
        + "green land in the same cell. a(n) counts the distinct pictures.",
    terms, offset: 1,
  });
}

/* 2. the integers that draw a grid no smaller integer already drew --
      one representative per picture, which is the more searchable form */
{
  const seen = new Set(), terms = [];
  for(let k = 1; k <= N; k++){
    const s = gridSig(k);
    if(!seen.has(s)){ seen.add(s); terms.push(k); }
  }
  SEQS.push({
    id: "firsts",
    name: "Integers whose fold-grid no smaller integer draws",
    note: "The least representative of each distinct grid.",
    terms, offset: 1,
  });
}

/* 3. integers whose lit cells all lie on the Fold.
      Inner and Outer both empty, so the whole value sits on the axis of
      reflection -- the numbers the construction treats as self-inverse. */
{
  const terms = [];
  for(let k = 1; k <= N; k++){
    const r = regionsOf(k);
    if(lit(r.fold) > 0 && lit(r.inner) === 0 && lit(r.outer) === 0) terms.push(k);
  }
  SEQS.push({
    id: "allfold",
    name: "Integers whose lit cells all lie on the fold's anti-diagonal",
    note: "Inner and Outer are both empty, so the number is carried entirely "
        + "by the cells the anti-transpose fixes.",
    terms, offset: 1,
  });
}

/* 4. lit cells on the Fold, per integer. The sequence the above thresholds. */
{
  const terms = [];
  for(let k = 1; k <= N; k++) terms.push(lit(regionsOf(k).fold));
  SEQS.push({
    id: "foldweight",
    name: "Number of lit cells on the fold's anti-diagonal for n",
    note: "How much of n the axis of reflection carries.",
    terms, offset: 1,
  });
}

/* 5. the side of the square n folds into. Grows in steps at the squares. */
{
  const terms = [];
  for(let k = 1; k <= N; k++) terms.push(stalkOf(k).n);
  SEQS.push({
    id: "side",
    name: "Side of the smallest square that holds n's signed-digit stalk",
    note: "ceil(sqrt(1 + number of bits of n)); the 1 is the reserved cell.",
    terms, offset: 1,
  });
}

/* ---- output -------------------------------------------------------------- */

function head(s){
  const first = s.terms.slice(0, 18).join(", ");
  return `\n${s.name}\n  ${s.note}\n  a(${s.offset}..) = ${first}${s.terms.length > 18 ? ", ..." : ""}`;
}

console.log(`# sequences from the chronochromatic fold, computed over 1..${N}`);
console.log(`# generated by tools/sequences.js from the site's own functions`);
for(const s of SEQS) console.log(head(s));

if(BFILES){
  const fs = require("fs");
  const dir = path.join(__dirname, "seq");
  if(!fs.existsSync(dir)) fs.mkdirSync(dir);
  for(const s of SEQS){
    const body = s.terms.map((t, i) => `${i + s.offset} ${t}`).join("\n") + "\n";
    fs.writeFileSync(path.join(dir, `b_${s.id}.txt`), body);
  }
  console.log(`\nwrote ${SEQS.length} b-files to tools/seq/`);
  console.log("search the OEIS by the leading terms, or by the description above.");
} else {
  console.log(`\n(run with --bfiles to write tools/seq/*.txt in OEIS b-file form)`);
}
